#! /bin/sh 
### BEGIN INIT INFO
# Provides: sonosremote
# Required-Start: $network lirc
# Required-Stop:
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 
# Short-Description: Run the Sonos Remote on startup
# Description:
### END INIT INFO

. /lib/lsb/init-functions

do_start() {
sleep 3    # make sure boot process is done, no more console messages
/home/pi/sonosremote/sonosremote.sh > /dev/null 2>&1 &
}

case "$1" in
  start)
        do_start
        ;;
  restart|reload|force-reload)
	#NOP
        ;;
  stop)
	kill $(ps aux | grep 'sonosremote' | awk '{print $2}')
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
